# Generated by Django 3.2 on 2023-10-27 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False, verbose_name='班级编号')),
                ('class_name', models.CharField(max_length=8, verbose_name='班级名称')),
            ],
            options={
                'verbose_name': 'Classes',
                'verbose_name_plural': 'Classess',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False, verbose_name='教师编号')),
                ('teacher_name', models.CharField(max_length=8, verbose_name='教师姓名')),
                ('teacher_class', models.ManyToManyField(to='app01.Classes', verbose_name='任教班级')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False, verbose_name='学生编号')),
                ('student_name', models.CharField(max_length=8, verbose_name='学生姓名')),
                ('student_gender', models.BooleanField(choices=[[0, 'male'], [1, 'female']], default=0, verbose_name='学生性别')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.classes', verbose_name='所属班级')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='classes',
            name='class_teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.teacher', verbose_name='班主任'),
        ),
    ]
